[package]
name = "ssr-core"
description = "traits for spaced repetition libs"
repository = "https://github.com/sineptic/ssr-core"
license = "MIT"
version = "0.17.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
